name: Remove blockmap

on:
  push:
    branches:
      - post-actions

jobs:
  delete_assets:
    runs-on: ubuntu-latest

    inputs:
      asset_ids:
        description: 'Comma-separated list of asset IDs'
        required: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete release assets
        id: delete_assets
        run: |
          IFS=',' read -ra asset_ids <<< "${{ inputs.asset_ids }}"
          for asset_id in "${asset_ids[@]}"; do
            echo "Deleting asset with ID: $asset_id"
            curl -X DELETE -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/kashamalasha/nightscout-widget-electron/releases/assets/$asset_id"
          done
          